---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/
namespace: mycluster
patches:
- target:
    kind: Namespace
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: mycluster
- target:
    kind: Cluster
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: mycluster
    - op: replace
      path: /spec/clusterNetwork/pods/cidrBlocks
      value: ["10.10.0.0/16"]
    - op: replace
      path: /spec/clusterNetwork/services/cidrBlocks
      value: ["10.20.0.0/16"]
    - op: replace
      path: /spec/controlPlaneRef/name
      value: mycluster-control-plane
    - op: replace
      path: /spec/infrastructureRef/name
      value: mycluster
- target:
    kind: AWSCluster
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: mycluster
    - op: replace
      path: /spec/sshKeyName
      value: mycluster-ssh
    - op: replace
      path: /spec/region
      value: eu-west-2
- target:
    kind: KubeadmControlPlane
    name: base-control-plane
  patch: |-
    - op: replace
      path: /metadata/name
      value: mycluster-control-plane
    - op: replace
      path: /spec/infrastructureTemplate/name
      value: mycluster-control-plane
    - op: replace
      path: /spec/version
      value: v1.18.0
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: AWSMachineTemplate
    name: base-control-plane
  patch: |-
    - op: replace
      path: /metadata/name
      value: mycluster-control-plane
    - op: replace
      path: /spec/template/spec/instanceType
      value: t3.medium
    - op: replace
      path: /spec/template/spec/sshKeyName
      value: mycluster-ssh
    - op: replace
      path: /spec/template/spec/additionalSecurityGroups/0/id
      value: mycluster-custom
- target:
    kind: MachineDeployment
    name: base-md-0
  patch: |-
    - op: replace
      path: /metadata/name
      value: mycluster-md-0
    - op: replace
      path: /spec/clusterName
      value: mycluster
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/bootstrap/configRef/name
      value: mycluster-md-0
    - op: replace
      path: /spec/template/spec/clusterName
      value: mycluster
    - op: replace
      path: /spec/template/spec/infrastructureRef/name
      value: mycluster-md-0
    - op: replace
      path: /spec/template/spec/version
      value: v1.18.0
- target:
    kind: AWSMachineTemplate
    name: base-md-0
  patch: |-
    - op: replace
      path: /metadata/name
      value: mycluster-md-0
    - op: replace
      path: /spec/template/spec/instanceType
      value: t3.medium
    - op: replace
      path: /spec/template/spec/sshKeyName
      value: mycluster-ssh
- target:
    kind: KubeadmConfigTemplate
    name: base-md-0
  patch: |-
    - op: replace
      path: /metadata/name
      value: mycluster-md-0
